"use client"

import "@/styles/globals.css";
import Link from "next/link";
import Image from "next/image";
// import type { Metadata } from "next"
import { Inter } from "next/font/google";
import Button from "@mui/material/Button";
import { usePathname } from "next/navigation";
import Divider from "@mui/material/Divider";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "사투리가 서툴러유",
//   description: "Generated by create next app",
// };`

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname(); // 현재 경로 가져오기

  // 특정 경로에서 header를 숨기기
  const hideHeader = pathname.startsWith("/game/in-game");

  return (
    <html lang="en" className="light">
      <body className={inter.className}>
          {!hideHeader && (
          <header>
            <div className="header">
              <Link href="/start">
                <Image src="/SSLogo.png" width={127.5} height={85} alt="SSLogo" />
              </Link>
              <div>
                <Link href="/login">
                  <Button 
                  variant="contained" 
                  sx={{
                    background: '#99DE83',
                    width: '90px',
                    height: '50px',
                    marginTop: '15px',
                    marginRight: '15px',
                    '&:hover': {
                      backgroundColor: '#7AB367',
                    },
                  }}
                  >
                    로그인
                  </Button>
                </Link>
              </div>
            </div>
            <Divider/>
          </header>
          )}
            {children}
          <footer className="footer">
            <div className="footer-content">
              <Image src="/SSLogo.png" width={127.5} height={85} alt="SSLogo"/>
              <div className="footer-links">
                <a href="/">Home</a>
                <a href="/about">About</a>
                <a href="/contact">Contact</a>
              </div>
              <p>&copy; 2024 My Next.js App. All rights reserved.</p>
            </div>
          </footer>
      </body>
    </html>
  );
}
